In [1]:
import numpy as np
myMatrizA=np.array([[1,2,3],[0,-4,6],[3,7,5]])
print "La matriz A es -->"
print myMatrizA

La matriz A es -->
[[ 1  2  3]
 [ 0 -4  6]
 [ 3  7  5]]


In [2]:
primeraFilaA=myMatrizA[0:1,1:3]
print "La primera fila es -->"
print primeraFilaA

La primera fila es -->
[[2 3]]


In [3]:
SegundaColumnaA=myMatrizA[0:3,1:2]
print "La segunda columna es -->"
print SegundaColumnaA

La segunda columna es -->
[[ 2]
 [-4]
 [ 7]]


In [4]:
invMyMatrizA=np.linalg.inv(myMatrizA)
print "La Matriz inversa de A es -->"
print invMyMatrizA

La Matriz inversa de A es -->
[[-6.2  1.1  2.4]
 [ 1.8 -0.4 -0.6]
 [ 1.2 -0.1 -0.4]]


In [5]:
invMyMatrizA10Decimales=np.around(invMyMatrizA, decimals=10)
print "La Matriz inversa de A con 10 digitos es -->"
print invMyMatrizA10Decimales

La Matriz inversa de A con 10 digitos es -->
[[-6.2  1.1  2.4]
 [ 1.8 -0.4 -0.6]
 [ 1.2 -0.1 -0.4]]


In [6]:
myMatrizAXinvmyMatrizA=np.matmul(myMatrizA,invMyMatrizA)
print "El resultado de la multiplicacion es -->"
print myMatrizAXinvmyMatrizA
myMatrizAXinvmyMatrizARounded=np.around(myMatrizAXinvmyMatrizA, decimals=0)
print "El resultado de la multiplicacion con redondeo es -->"
print myMatrizAXinvmyMatrizARounded

El resultado de la multiplicacion es -->
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 4.44089210e-15 -1.11022302e-16  1.00000000e+00]]
El resultado de la multiplicacion con redondeo es -->
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [7]:
determinantemyMatrizA=np.linalg.det(myMatrizA)
print "El determinante de la matriz A es -->"
print determinantemyMatrizA

El determinante de la matriz A es -->
10.000000000000007


In [8]:
valoresPropios, vectoresPropios= np.linalg.eig(myMatrizA)
print "Los valores propios de A es son -->"
print valoresPropios
print "Los vectores propios de A es son -->"
print vectoresPropios

Los valores propios de A es son -->
[ 9.48845758 -0.14348759 -7.34496998]
Los vectores propios de A es son -->
[[ 0.38619329  0.94502015  0.03425966]
 [ 0.37489703 -0.27508868 -0.87292444]
 [ 0.84279711 -0.17681382  0.48665101]]


In [9]:
myMatrizB=np.array([[0,1],[1,0],[2,3]])
print "La matriz B es -->"
print myMatrizB

La matriz B es -->
[[0 1]
 [1 0]
 [2 3]]


In [10]:
operacion1=np.matrix.transpose(myMatrizB)
operacion2=np.matmul(operacion1,myMatrizB)
operacion3=np.linalg.inv(operacion2)
myMatrizJ=np.matmul(operacion3,operacion1)
print "La seudo Inversa de la matriz B es -->"
print myMatrizJ

La seudo Inversa de la matriz B es -->
[[-0.42857143  0.71428571  0.14285714]
 [ 0.35714286 -0.42857143  0.21428571]]


In [11]:
resultado=np.matmul(myMatrizJ,myMatrizB)
print "El resultado de la multiplicacion es -->"
print resultado
resultadoRedondeado=np.around(resultado, decimals=0)
print "El resultado de la multiplicacion con redondeo es -->"
print resultadoRedondeado

El resultado de la multiplicacion es -->
[[ 1.00000000e+00  3.33066907e-16]
 [-1.66533454e-16  1.00000000e+00]]
El resultado de la multiplicacion con redondeo es -->
[[ 1.  0.]
 [-0.  1.]]


In [12]:
dimensionDeI = np.shape(resultado)
print "La dimension de I es -->"
print dimensionDeI

La dimension de I es -->
(2, 2)
